env:
  BUILDKITE_ANALYTICS_TOKEN: "fWD5V1t8bzGtArDrZUJdRuzX"

steps:
  - label: ":rspec: RSpec unit"
    command: .buildkite/steps/run
    key: unit
    agents:
      queue: "hosted-queue"
    parallelism: 2
    env:
      BUILDKITE_SPLITTER_TEST_FILE_PATTERN: "spec/unit/*_spec.rb"
