env:
  BUILDKITE_ANALYTICS_TOKEN: "fWD5V1t8bzGtArDrZUJdRuzX"

steps:
  - label: ":rspec: RSpec"
    command: .buildkite/steps/run
    key: run
    agents:
      queue: "hosted-queue"
    parallelism: 5
