steps:
  - label: ":rspec: RSpec unit"
    command: .buildkite/steps/run
    key: unit
    agents:
      queue: "hosted-queue"
    parallelism: 2
    env:
      BUILDKITE_SPLITTER_TEST_FILE_PATTERN: "spec/unit/**/*_spec.rb"

  - label: "Acceptance"
    command: .buildkite/steps/run
    key: acceptance
    agents:
      queue: "hosted-queue"
    parallelism: 2
    env:
      BUILDKITE_SPLITTER_TEST_FILE_PATTERN: "spec/acceptance/**/*_spec.rb"

  - label: "Update Test Ownership?"
    plugins:
      - monorepo-diff#v1.0.1:
          watch:
            - path: .buildkite/TESTOWNERS
              config:
                trigger: update-test-ownership
